services:
  - type: web
    name: sgos
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false          # lo ingresas manualmente en el panel de Render
      - key: FLASK_ENV
        value: production
